## Version 2026/07/21 - Review configuration changes before adopting updates.
listen 443 ssl;
listen [::]:443 ssl;
listen 443 quic;
listen [::]:443 quic;

ssl_certificate /config/keys/cert.crt;
ssl_certificate_key /config/keys/cert.key;

# HTTP3 configuration
add_header Alt-Svc 'h3=":$server_port"; ma=86400' always;
