# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;

# Proxy Connection Settings
proxy_read_timeout 240s;
proxy_send_timeout 240s;

# Use common proxy settings
include /config/nginx/snippets/proxy-common.conf;
