## Version 2026/07/19 - Review configuration changes before adopting updates.
# Disable retries mid-stream
proxy_next_upstream off;

# Disable proxy buffering
proxy_buffering off;
proxy_request_buffering off;

# Don't cache
proxy_cache off;

# Use longer timeouts for streams
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;
send_timeout 3600s;

# Use common proxy settings
include /config/nginx/snippets/proxy-common.conf;
