## Version 2026/07/19 - Review configuration changes before adopting updates.
# Disable retries on dropped WebSocket connections
proxy_next_upstream off;

# Don't cache
proxy_cache off;

# Use longer timeouts for persistent WebSocket connections
proxy_send_timeout 86400s;
proxy_read_timeout 86400s;
send_timeout 86400s;

# Use common proxy settings
include /config/nginx/snippets/proxy-common.conf;
