# Disable retries on dropped WebSocket connections
proxy_next_upstream off;

# Use longer timeouts for persistent WebSocket connections
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;
send_timeout 3600s;

# Use common proxy settings
include /config/nginx/snippets/proxy-common.conf;
