## Version 2026/07/19 - Review configuration changes before adopting updates.
# Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;

# Disable proxy request buffering
proxy_request_buffering off;

# Don't cache
proxy_cache off;

# Use longer timeouts for uploads
proxy_read_timeout 600s;
proxy_send_timeout 3600s;
send_timeout 3600s;

# Disable client body size limit for uploads
client_max_body_size 0;

# Use common proxy settings
include /config/nginx/snippets/proxy-common.conf;
