## Version 2026/07/21 - Review configuration changes before adopting updates.
include /config/nginx/snippets/listen-https.conf;
include /config/nginx/snippets/hsts.conf;
include /config/nginx/snippets/geoip-block.conf;
include /config/nginx/snippets/no-robots.conf;
include /config/nginx/snippets/security-headers.conf;
