## Version 2026/07/21 - Review configuration changes before adopting updates.

# Drop requests for unknown hosts.
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    return 444;
}

server {
    listen 443 ssl reuseport default_server;
    listen [::]:443 ssl reuseport default_server;
    listen 443 quic reuseport default_server;
    listen [::]:443 quic reuseport default_server;

    ssl_certificate /config/keys/cert.crt;
    ssl_certificate_key /config/keys/cert.key;

    access_log off;
    ssl_reject_handshake on;

    server_name _;
}
