## Version 2026/07/19 - Review configuration changes before adopting updates.
# Drop requests for unknown hosts.
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    return 444;
}

server {
    listen 443 ssl reuseport default_server;
    listen [::]:443 ssl reuseport default_server;
    listen 443 quic reuseport default_server;
    listen [::]:443 quic reuseport default_server;

    access_log off;
    ssl_reject_handshake on;

    server_name _;
}
