gzip on;
gzip_comp_level 4;
gzip_min_length 512;
gzip_proxied any;
gzip_vary on;
gzip_types
  text/css
  text/javascript
  text/js
  text/plain
  text/richtext
  text/xml
  text/x-component
  text/x-markdown
  text/csv
  text/vtt
  text/yaml
  text/x-yaml
  application/javascript
  application/json
  application/problem+json
  application/schema+json
  application/ld+json
  application/vnd.api+json
  application/manifest+json
  application/nd+json
  application/x-javascript
  application/xhtml+xml
  application/xml
  application/atom+xml
  application/rss+xml
  image/svg+xml;
