#!/bin/sh
set -eu

config=
database_dir=
while getopts "f:d:" option; do
    case "${option}" in
        f) config="${OPTARG}" ;;
        d) database_dir="${OPTARG}" ;;
        *) exit 2 ;;
    esac
done

grep -q '^AccountID file-account$' "${config}"
grep -q '^LicenseKey file-license$' "${config}"
grep -q '^EditionIDs GeoLite2-Country$' "${config}"
mkdir -p "${database_dir}"
: > "${database_dir}/GeoLite2-Country.mmdb"
