name: Delete old container packages

on:
  workflow_dispatch: # Allows manual triggering
  # Or schedule: # For automated deletion at regular intervals
  #   cron: '0 0 * * *' # Example: run daily at midnight UTC

jobs:
  delete-versions:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Grant write permissions to packages
      contents: read # Grant read permissions to repository contents

    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'docker-nginx' # Replace with your package name
          package-type: 'container' # Replace with your package type (e.g., 'container', 'maven', 'nuget', 'rubygems')
          min-versions-to-keep: 1 # Keep only the latest version
          token: ${{ secrets.GITHUB_TOKEN }} # Use the default GITHUB_TOKEN or a PAT with delete:packages scope
